name: solana_utils
description: Solana address and transaction signature validator/formatter, and basic transaction details.
version: 0.0.1
repository: https://github.com/Immadominion/solana_utils
homepage: https://github.com/Immadominion/solana_utils
license: MIT

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
